apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: visitors-sub
  namespace: marketplace
spec:
  channel: stable
  name: visitors-ansible-operator
  source: davarski-operators
  sourceNamespace: marketplace
