apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "example.com/v1",
          "kind": "VisitorsApp",
          "metadata": {
            "name": "example-visitorsapp"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
  name: visitors-ansible-operator.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: VisitorsApp
      name: visitorsapps.example.com
      version: v1
      displayName: Visitors Site Application
      description: Full stack for the Visitors Site
      resources:
      - kind: Service
        version: v1
      - kind: Deployment
        version: v1
      specDescriptors:
      - displayName: Size
        description: The number of backend pods to create
        path: size
      - displayName: Title
        description: Title to display on the web UI dashboard
        path: title
      statusDescriptors:
      - displayName: Backend Image
        description: Full name and version of the image used to create the backend service
        path: backendImage
      - displayName: Frontend Image
        description: Full name and version of the image used to create the frontend service
        path: frontendImage
  description: Operator for installing the Visitors Site application
  displayName: Visitors Ansible Operator
  install:
    spec:
      deployments:
      - name: visitors-ansible-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: visitors-ansible-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: visitors-ansible-operator
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: davarski/visitors-ansible-operator:0.1
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: visitors-ansible-operator
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: davarski/visitors-ansible-operator:0.1
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: visitors-ansible-operator
              volumes:
              - emptyDir: {}
                name: runner
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - visitors-ansible-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - example.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: visitors-ansible-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: visitors-ansible-operator.v0.0.0
  version: 1.0.0
